#!/bin/sh

module="scull"
device="scull"
mode="664"

if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

insmod ./$module.ko $* || exit 1

usleep 200000
major=$(awk '$2=="scull" {print $1}' /proc/devices)

echo "MAJOR: " $major

rm -f /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
ln -sf ${device}0 /dev/${device}
chgrp $group /dev/${device}[0-3] 
chmod $mode  /dev/${device}[0-3]

# group="wheel"
# # grep -1 '^staff:' /etc/group || group="wheel"

# chgrp $group /dev/${device}[0-3]
# chmod $mode /dev/${device}[0-3]